import Head from 'next/head';
import { atom, useAtom } from 'jotai';
import type { NextPage } from 'next';

const countAtom = atom(0);

const Home: NextPage = () => {
  const [count, setCount] = useAtom(countAtom);
  const onClickHandler = () => setCount((pre) => pre + 1);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={onClickHandler}>버튼</button>
        <div>{count}</div>
        <h1>Welcome</h1>
        <div>Next.js</div>
      </main>
      <footer>footer</footer>
    </div>
  );
};

export default Home;
