import Layout from '@/components/common/Layout';
import ExchangeRateBox from '@/components/dividend/ExchangeRate';
import ModeController from '@/components/ModeController';
import CommonCenter from '@/components/common/Center';
import CommonHeader from '@/components/common/Header';
import DetailStocksSection from '@/components/portfolio/portfolioSections/DetailStocksSection';
import SimpleDividentScheduleSection from '@/components/portfolio/portfolioSections/SimpleDividentScheduleSection';
import ChartSection from '@/components/portfolio/portfolioSections/ChartSection';
import TotalStatisticsSection from '@/components/portfolio/portfolioSections/TotalStatisticsSection';
import { useMyPortFolio } from '@/hook/useMyPortFolio';
import NotifyMessageSection from '@/components/portfolio/portfolioSections/NotifyMessageSection';
import { CircularProgress } from '@mui/material';

import Head from 'next/head';

const MainPage = () => {
  const { myPortFolioData, status } = useMyPortFolio();

  if (status === 'loading') {
    return (
      <Layout>
        <CommonCenter>
          <CircularProgress />
        </CommonCenter>
      </Layout>
    );
  }

  const hasNotAssets = myPortFolioData?.assetDetails.length;

  if (status === 'success' && hasNotAssets) {
    return (
      <>
        <Head>
          <title>나의 포트폴리오 - 스노우볼</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <CommonHeader>
            <ModeController />
          </CommonHeader>
          <ExchangeRateBox />
          <ChartSection />
          <TotalStatisticsSection />
          <SimpleDividentScheduleSection />
          <DetailStocksSection />
          <NotifyMessageSection />
        </Layout>
      </>
    );
  }

  return null;
};

export default MainPage;
